# uso le funzioni della libreria turtle
import turtle                

# mosse della tartaruga bart (non serve leggere: basta eseguire)

bart = turtle.Turtle()
bart.color("red")
bart.pensize(5)
bart.penup()
bart.setpos(310,-10)
bart.pendown()
bart.right(180)
bart.forward(10)
bart.left(90)
bart.forward(290)
bart.right(90)
bart.forward(600)
bart.right(90)
bart.forward(600)
bart.right(90)
bart.forward(600)
bart.right(90)
bart.forward(290)
bart.left(90)
bart.forward(10)
bart.penup()
bart.setpos(0,-200)
bart.pendown()
bart.left(90)
bart.forward(400)

# mosse della tartaruga pippo

pippo = turtle.Turtle()
pippo.penup()
pippo.setpos(-200,0)
pippo.pendown()
pippo.forward(20)

# aggiungere il codice qui sotto (non modificare le righe sopra questo commento)

g = turtle.Turtle()
g.color("black")
g.pensize(5)
g.left(180)
g.penup()
g.forward(50)
g.pendown()
g.left(90)
g.forward(250)
g.left(90)
g.forward(200)
g.left(90)
g.forward(250)
g.right(90)
g.forward(250)

turtle.done()